"""Add unique constraint to habit_records

Revision ID: f2f0bacba3dc
Revises: dfbd7d1d237c
Create Date: 2025-06-17 19:45:16.077000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f0bacba3dc'
down_revision: Union[str, Sequence[str], None] = 'dfbd7d1d237c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_habit_date_uc', 'habit_records', ['habit_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_habit_date_uc', 'habit_records', type_='unique')
    # ### end Alembic commands ###
